[workspace]
members = [
    "crates/steamless-core",
    "crates/steamless-c-abi",
    "crates/steamless-cli"
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["Antigravity Engineering"]
license = "GPL-3.0-only"
repository = "https://github.com/staernid/steamless-rs"

