[package]
name = "steamless-c-abi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Native C ABI shared library export for Steamless engine"

[lib]
name = "steamless_c"
crate-type = ["cdylib", "rlib"]

[dependencies]
steamless-core = { path = "../steamless-core" }
