[package]
name = "steamless-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Standalone command line executable for Steamless DRM unpacker"

[[bin]]
name = "steamless"
path = "src/main.rs"

[dependencies]
steamless-core = { path = "../steamless-core" }
